language: go

go:
  - 1.14

env:
  - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

before_install:
  - go get -u github.com/mattn/goveralls

script:
  - go mod download
  - go test ./... -covermode=count -coverprofile=coverage.cov
  - goveralls -coverprofile=profile.cov -service=travis-ci

notifications:
  email:
    on_success: change
    on_failure: always