app:
  port: 1323
  bodyLimit: 512K
  requestStoreTime: 24h
  clientUrl: http://localhost:8080
  forbiddenHeaders:
    - X-Forwarded-For
    - X-Forwarded-Port
    - X-Forwarded-Proto
    - X-Request-Start
rate:
  limit: 100
  period: 1m

redis:
  host: localhost
  port: 6379
  password:
  db: 0