app:
  port: 1323
  bodyLimit: 256K
  requestStoreTime: 24h
  forbiddenHeaders:
    - X-Forwarded-For
    - X-Forwarded-Port
    - X-Forwarded-Proto
    - X-Request-Start
  historyCount: 5
  maxRequestCount: 50

rate:
  limit: 100
  period: 1m

redis:
  host: localhost
  port: 6379
  password:
  db: 0