basePath: /
host: api.istekbin.com
info:
  contact:
    name: API Support
    url: https://github.com/BatuhanKucukali/istekbin-api/issues/new
  description: Istekbin is a free service that allows you to collect http request.
  license:
    name: Apache 2.0
    url: https://github.com/BatuhanKucukali/istekbin-api/blob/master/LICENSE
  title: Istekbin API
  version: "1.0"
paths: {}
swagger: "2.0"
